"""Create initial tables

Revision ID: 28ba806a1a29
Revises: 
Create Date: 2025-08-13 16:49:53.306487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28ba806a1a29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officialdata_agencies',
    sa.Column('agency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_name', sa.String(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('agency_id'),
    sa.UniqueConstraint('agency_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(), nullable=False),
    sa.Column('longitude', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'VERIFIED_VIOLATION', name='reportstatus'), nullable=True),
    sa.Column('violation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('original_image_url', sa.String(), nullable=True),
    sa.Column('anonymized_image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('ocrextractions',
    sa.Column('ocr_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('ocr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocrextractions')
    op.drop_table('images')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_table('officialdata_agencies')
    # ### end Alembic commands ###
